# Generated by Django 4.0.2 on 2022-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='client',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hisob raqami'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank INN'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_mfo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank MFO'),
        ),
        migrations.DeleteModel(
            name='ClientBankDetail',
        ),
    ]
