# Generated by Django 4.0.2 on 2022-02-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Kassa nomi')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
            },
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Chiqim turi nomi')),
                ('to_supplier', models.BooleanField(default=False, verbose_name="Ta'minotchiga")),
                ('to_employee', models.BooleanField(default=False, verbose_name='Hodim uchun maosh')),
            ],
            options={
                'verbose_name': 'Chiqim turi',
                'verbose_name_plural': 'Chiqim turlari',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Valyuta nomi')),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': 'Valyutalar',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('type', models.CharField(choices=[('Client', 'Client'), ('Extra', 'Extra')], default='Normal', max_length=255, verbose_name='Kirim turi')),
                ('extra_income_title', models.CharField(blank=True, max_length=255, verbose_name='Extra kirim nomi')),
                ('payment_type', models.CharField(choices=[('Naqd', 'Naqd'), ('Plastik', 'Plastik'), ('Bank', 'Bank')], max_length=50, verbose_name="To'lov turi")),
                ('total_sum', models.PositiveIntegerField(verbose_name='Summa miqdori')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirim',
            },
        ),
        migrations.CreateModel(
            name='SubCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Subkategoriya nomi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.costtype', verbose_name='Chiqim turi')),
            ],
            options={
                'verbose_name': 'Chiqim subkategoriya',
                'verbose_name_plural': 'Chiqim subkategoriya',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('to_where', models.CharField(max_length=255, verbose_name='Qayerga (kimga)?')),
                ('bonus', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bonus')),
                ('bonus_reason', models.CharField(blank=True, max_length=255, verbose_name='Bonus sababi')),
                ('fine', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jarima')),
                ('fine_reason', models.CharField(blank=True, max_length=255, verbose_name='Jarima sababi')),
                ('payment_type', models.CharField(choices=[('Naqd', 'Naqd'), ('Plastik', 'Plastik'), ('Bank', 'Bank')], max_length=50, verbose_name="To'lov turi")),
                ('total_sum', models.PositiveIntegerField(verbose_name='Summa miqdori')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cashbox', verbose_name='Kassa')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.costtype', verbose_name='Chiqim turi')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqim',
            },
        ),
    ]
