# Generated by Django 4.0.2 on 2022-02-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sub_cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.subcosttype', verbose_name='Sub kategoriya'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('bank', 'bank')], max_length=50, verbose_name="To'lov turi"),
        ),
    ]
