# Generated by Django 4.0.2 on 2022-02-22 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hisob raqami'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank INN'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_mfo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank MFO'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon raqami mana bunday bo'lishi kerak: `998901234567`", regex='^((\\+998)|(998))\\d{9}$')], verbose_name='Asosiy telefon raqami'),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
