# Generated by Django 4.0.2 on 2022-02-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('supplier', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('quantity', models.FloatField(verbose_name='Miqdori')),
                ('valid_status', models.BooleanField(verbose_name='Qayta ishlashga yaroqlik')),
                ('returned_status', models.BooleanField(verbose_name='Sotuvdan qaytgan')),
            ],
            options={
                'verbose_name': 'Buzilgan mahsulot',
                'verbose_name_plural': 'Buzilgan mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='LeaveInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('responsible', models.CharField(blank=True, max_length=50, verbose_name="Mas'ul shaxs")),
                ('status', models.CharField(choices=[('in-progress', 'in-progress'), ('waiting', 'waiting'), ('saved', 'saved'), ('cancelled', 'cancelled')], default='Waiting', max_length=30)),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('further', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Chiqish faktura',
                'verbose_name_plural': 'Chiqish fakturalar',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name="O'lchov birligi nomi")),
            ],
            options={
                'verbose_name': "O'lchov birligi",
                'verbose_name_plural': "O'lchov birliklari",
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='Model')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('type', models.CharField(choices=[('raw', 'raw'), ('semi-finished', 'semi-finished'), ('finished', 'finished'), ('inventory', 'inventory')], max_length=255, verbose_name='Turi')),
                ('arrival_price', models.PositiveIntegerField(default=0, verbose_name='Tan narxi')),
                ('selling_price', models.PositiveIntegerField(default=0, verbose_name='Sotish narxi')),
                ('shelf_life', models.CharField(max_length=50, verbose_name='Yaroqlilik muddati')),
                ('critical_quantity', models.FloatField(default=0.0, verbose_name='Kritik miqdori')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('further', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency', verbose_name='Valyuta')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Guruh nomi')),
            ],
            options={
                'verbose_name': 'Mahsulot guruhi',
                'verbose_name_plural': 'Mahsulot guruhlari',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Ombor nomi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
            },
        ),
        migrations.CreateModel(
            name='ReceiveInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('responsible', models.CharField(blank=True, max_length=50, verbose_name="Mas'ul shaxs")),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('saved', 'saved'), ('cancelled', 'cancelled')], default='Waiting', max_length=30, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('further', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage', verbose_name='Ombor')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'verbose_name': 'Qabul faktura',
                'verbose_name_plural': 'Qabul fakturalar',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('type', models.CharField(choices=[('receive', 'receive'), ('leave', 'leave'), ('plan', 'plan')], max_length=50, verbose_name='Turi')),
                ('quantity', models.FloatField(verbose_name='Miqdori')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency', verbose_name='Valyuta')),
                ('leave_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.leaveinvoice', verbose_name='Chiqish faktura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product', verbose_name='Mahsulot')),
                ('receive_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.receiveinvoice', verbose_name='Kirish faktura')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage', verbose_name='Ombor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.productgroup', verbose_name='Guruhi'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.measurementunit', verbose_name="O'lchov birligi"),
        ),
    ]
