# Generated by Django 4.0.2 on 2022-02-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectiveproduct',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.storage'),
            preserve_default=False,
        ),
    ]
