# Generated by Django 4.0.2 on 2022-02-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveInvoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('quantity', models.FloatField(verbose_name='Miqdori')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.receiveinvoice', verbose_name='Faktura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product', verbose_name='Mahsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiveInvoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('quantity', models.FloatField(verbose_name='Miqdori')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.receiveinvoice', verbose_name='Faktura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product', verbose_name='Mahsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
