# Generated by Django 4.0.2 on 2022-02-19 21:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
        ('finance', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='storage',
            field=models.ManyToManyField(to='storage.Storage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yashash manzili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon raqami mana bunday bo'lishi kerak: `998901234567`", regex='^((\\+998)|(998))\\d{9}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Direktor', 'Direktor'), ("Sotuv boshlig'i", "Sotuv boshlig'i"), ('Sotuv meneger', 'Sotuv meneger'), ('Omborchi', 'Omborchi'), ("Ta'minotchi", "Ta'minotchi"), ('Texnolog', 'Texnolog'), ("Seh boshlig'i", "Seh boshlig'i"), ('Nazoratchi', 'Nazoratchi'), ('Kassir', 'Kassir')], max_length=255, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.PositiveIntegerField(default=0, verbose_name='Maosh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Otasining ismi'),
        ),
    ]
