# Generated by Django 4.0.2 on 2022-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'director'), ('sales-director', 'sales-director'), ('sales-manager', 'sales-manager'), ('stockman', 'stockman'), ('supplier', 'supplier'), ('technolog', 'technolog'), ('production-director', 'production-director'), ('controller', 'controller'), ('cashier', 'cashier')], max_length=255, verbose_name='Lavozim'),
        ),
    ]
