# Generated by Django 4.0.2 on 2022-02-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_defectiveproduct_storage'),
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='storages',
            field=models.ManyToManyField(blank=True, to='storage.Storage', verbose_name='Omborlar'),
        ),
    ]
